"""add applications

Revision ID: 7c94e7ec1ddc
Revises: 035aa261bb96
Create Date: 2018-04-20 15:23:04.626253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c94e7ec1ddc'
down_revision = '035aa261bb96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicants',
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.Column('applied_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['applied_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicants')
    # ### end Alembic commands ###
